language: go

go:
- '1.11.x'

install:
- mkdir $HOME/src
- cd $HOME/src
- git clone https://github.com/gohugoio/hugo.git
- cd hugo
- git checkout v0.54.0
- go install
- cd $TRAVIS_BUILD_DIR
- sudo pip install Pygments
- sudo pip install s3cmd

before_script:
- hugo version
- pygmentize -V
- python --version
- s3cmd --version

script:
- make build

after_success:
- ls public/

deploy:
  skip_cleanup: true
  provider: script
  script: s3cmd --access_key="${AWS_ACCESS_KEY_ID}" --secret_key="${AWS_SECRET_ACCESS_KEY}" --region=$AWS_REGION sync --delete-removed --acl-public --guess-mime-type --no-mime-magic --recursive public/ s3://$AWS_BUCKET/
  on:
    branch: master

after_deploy:
- s3cmd --access_key="${AWS_ACCESS_KEY_ID}" --secret_key="${AWS_SECRET_ACCESS_KEY}" --region=$AWS_REGION ls s3://$AWS_BUCKET/
